### PR TITLE
New param system and other changes

### PR DESCRIPTION
**Pull request by caseyjlaw**
Hey Sarah,
  I made several changes on my side, but I don't think they should collide with yours. Anyway, I'm hopeful this is a simple merge. If not, you can make a pull request to me and I'll take care of it.
  Changes:
-- Removed nohup stuff and now use screen to start workers
-- Moved all pipeline parameter definition to a python (text) file. rtpipe has lots of changes to support that, but I think it will make things much more stable and flexible.
-- That changes makes it possible to define the pipeline "state" object with a single call to rtpipe.RT. No need to call rtpipe.parsesdm first.

  These changes are tested in rtpipe and queue_rtpipe.py, but not with the daemon.

### CODE REVIEW

**Comment by caseyjlaw** [comment]
Oops. This will be harder to merge. I'll close this for now and we can discuss more later.

**Comment by xiggystardust** [comment]
Hey Casey -- I don't think there should be any conflicts? I have only ever worked on CBE_boss_daemon.py (as far as I remember) and lately I'm only working on an external tester program that's not checked in to the repo...

**Comment by caseyjlaw** [comment]
Ok, I'll reopen the pull request. This may be a set of small conflicts (like names of worker nodes), but it still will require manually merging.
If you don't want to do that, I'll close the pull request and ask that you send me one for manual merging. It is a hassle, so it could wait until you have something ready to test with your new pyinotify stuff.

**Comment by xiggystardust** [comment]
I'm doing a big overhaul based on recent tests. So what I will probably end up doing is just taking your CBE_boss code, building my new stuff directly into there, and then we can both just take that and stick it back in. This will work best if you don't change CBE_boss_daemon while I'm overhauling, so I'll let you know when I'm doing it. For now, feel free to do what you want (I'll likely get to this thurs or fri---running a lot of testing today)

**Comment by caseyjlaw** [comment]
Sounds good.

**Comment by caseyjlaw** [comment]
It looks like this pull request is attached to a very old fork of the realfast code. I'll close it for now, but we should discuss how to get the commit in.

**Pull request closed without merging**
